name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  release:
    types:
      - created

jobs:
  build:
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'

      - name: Check Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Make bin directory
        run: mkdir -p bin

      - name: Build (linux/amd64)
        env:
          GOOS: linux
          GOARCH: amd64
        run: go build -o ./bin/sealedsecrets-linux-amd64 .

      - name: Build (linux/arm64)
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -o ./bin/sealedsecrets-linux-arm64 .

      - name: Build (darwin/amd64)
        env:
          GOOS: darwin
          GOARCH: amd64
        run: go build -o ./bin/sealedsecrets-darwin-amd64 .

      - name: Build (darwin/arm64)
        env:
          GOOS: darwin
          GOARCH: arm64
        run: go build -o ./bin/sealedsecrets-darwin-arm64 .

      - name: Build (windows/amd64)
        env:
          GOOS: windows
          GOARCH: amd64
        run: go build -o ./bin/sealedsecrets-windows-amd64 .

      - name: Build (windows/arm64)
        env:
          GOOS: windows
          GOARCH: arm64
        run: go build -o ./bin/sealedsecrets-windows-arm64 .

      - name: Add release files
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/sealedsecrets-linux-amd64
            bin/sealedsecrets-linux-arm64
            bin/sealedsecrets-darwin-amd64
            bin/sealedsecrets-darwin-arm64
            bin/sealedsecrets-windows-amd64
            bin/sealedsecrets-windows-arm64
