name: Release

on:
  push:
    branches:
      - main
    tags:
      - v*
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            asset_name: sealedsecrets-linux-amd64
          - os: linux
            arch: arm64
            asset_name: sealedsecrets-linux-arm64
          - os: windows
            arch: amd64
            asset_name: sealedsecrets-windows-amd64.exe
          - os: windows
            arch: arm64
            asset_name: sealedsecrets-windows-arm64.exe
          - os: darwin
            arch: amd64
            asset_name: sealedsecrets-darwin-amd64
          - os: darwin
            arch: arm64
            asset_name: sealedsecrets-darwin-arm64
    name: Build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21.0'

      - name: Check Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      - name: Make bin directory
        run: mkdir -p bin

      - name: Build (${{ matrix.os }}/${{ matrix.arch }})
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o "./bin/${{ matrix.asset_name }}" .

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "bin/${{ matrix.asset_name }}"
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
